language: python
python:
  - "2.6"
  - "2.7"
services:
  - couchdb
sudo: false
before_script:
  - pip install coveralls unittest2 nose-testconfig mock
script:
  - python setup.py install
  - python setup.py nosetests
after_success:
  - coveralls
