language: python
python: 
  - "2.7"
branches:
  only:
    - master
services:
  - couchdb
before_script:
  - pip install coveralls
script:
  - python setup.py install
  - nosetests tests
after_success:
  - coveralls
